# Generated by Django 4.2.16 on 2024-09-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_rename_user_user2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User2',
            new_name='User',
        ),
    ]
